version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: paylink-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paylink_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  paylink-system:
    build: .
    container_name: paylink-system
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paylink_core
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: "mMwzAbJNyjyrOFcduyDoGsnJOfQdr/lM65h3mNhcWZg="

volumes:
  postgres_data:
